services:
  load-generator:
    container_name: load-generator
    hostname: load-generator
    image: corrosion:${SHORT_COMMIT}
    command: ["rust-load-generator", "corrosion1:8080", "corrosion2:8080", "corrosion3:8080"]
    environment:
    - RUST_LOG=info
    - RUST_BACKTRACE=full
    annotations:
      com.antithesis.exclude.faults: "all"

  corrosion1:
    container_name: corrosion1
    hostname: corrosion1
    image: corrosion:${SHORT_COMMIT}
    volumes:
      - ./volumes/corrosion1:/var/lib/corrosion

  corrosion2:
    container_name: corrosion2
    hostname: corrosion2
    image: corrosion:${SHORT_COMMIT}
    volumes:
      - ./volumes/corrosion2:/var/lib/corrosion

  corrosion3:
    container_name: corrosion3
    hostname: corrosion3
    image: corrosion:${SHORT_COMMIT}
    volumes:
      - ./volumes/corrosion3:/var/lib/corrosion 

  corro-client:
    container_name: corro-client
    hostname: corro-client
    image: corro-client:${SHORT_COMMIT}
    init: true
    volumes:
      - ./volumes/corrosion1:/var/lib/corrosion1
      - ./volumes/corrosion2:/var/lib/corrosion2
      - ./volumes/corrosion3:/var/lib/corrosion3
    annotations:
      com.antithesis.exclude.faults: "all"

  consul:
    container_name: consul
    hostname: consul
    image: consul:1.15.4
    command: consul agent -data-dir=/consul/data -config-dir=/consul/config -dev -server -bind=0.0.0.0 -client=0.0.0.0 -log-level=debug
    annotations:
      com.antithesis.exclude.faults: "all"
