[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "force-frame-pointers",
    "-C", "symbol-mangling-version=v0",
    "-Z", "share-generics=y",
    "--cfg", "tokio_unstable"
]

[target.aarch64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]
