[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "force-frame-pointers",
    "-C", "symbol-mangling-version=v0",
    "--cfg", "tokio_unstable"
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "force-frame-pointers",
    "-C", "symbol-mangling-version=v0",
    "--cfg", "tokio_unstable"
]

[target.aarch64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]

[env]
LIBSQLITE3_FLAGS = "-DSQLITE_DEBUG -DSQLITE_OMIT_SHARED_CACHE"
